using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.InternationalTaxonomyClassifications.ReadInternationalTaxonomyClassification;

public record struct ReadInternationalTaxonomyClassificationQueryResponse(InternationalTaxonomyClassification InternationalTaxonomyClassification) { }