namespace WHO.BioHub.DataManagement.Core.UseCases.InternationalTaxonomyClassifications.ReadInternationalTaxonomyClassification;

public record struct ReadInternationalTaxonomyClassificationQuery(Guid Id) { }