using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformations.UpdateMaterialShippingInformation;

public record struct UpdateMaterialShippingInformationCommandResponse(MaterialShippingInformation MaterialShippingInformation) { }