namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.UpdateMaterialShippingInformationHistory;

public record struct UpdateMaterialShippingInformationHistoryCommand(Guid Id) { }