namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.DeleteMaterialShippingInformationHistory;

public record struct DeleteMaterialShippingInformationHistoryCommand(Guid Id) { }