using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialClinicalDetailsHistory.UpdateMaterialClinicalDetailHistory;

public record struct UpdateMaterialClinicalDetailHistoryCommandResponse(MaterialClinicalDetailHistory MaterialClinicalDetailHistory) { }