namespace WHO.BioHub.PublicData.Core.UseCases.InternationalTaxonomyClassifications.ListInternationalTaxonomyClassifications;

public record struct ListInternationalTaxonomyClassificationsQuery(Guid Id) { }