using Microsoft.AspNetCore.Http;
using WHO.BioHub.Shared.Dto;
using WHO.BioHub.Shared.Enums;

namespace WHO.BioHub.DataManagement.Core.UseCases.WorklistFromBioHubItems.UpdateWorklistFromBioHubItem;

public record struct UpdateWorklistFromBioHubItemCommand(
    Guid Id,
    RoleType? RoleType,
    Guid? UserLaboratoryId,
    Guid? UserBioHubFacilityId,
    WorklistFromBioHubStatus CurrentStatus,
    Guid? UserId,
    bool? LastSubmissionApproved,
    string Comment,
    Guid? OriginalDocumentTemplateSMTA2DocumentId,
    DocumentFileType? DocumentTemplateFileType,
    IFormFile? File,
    IEnumerable<string> UserPermissions,
    FillingOption? Annex2FillingOption,
    IEnumerable<WorklistItemUserDto> LaboratoryFocalPoints,
    IEnumerable<WorklistFromBioHubItemMaterialDto> WorklistFromBioHubItemMaterials,
    IEnumerable<WorklistFromBioHubItemAnnex2OfSMTA2ConditionDto> WorklistFromBioHubItemAnnex2OfSMTA2Conditions,
    IEnumerable<WorklistFromBioHubItemBiosafetyChecklistOfSMTA2Dto> WorklistFromBioHubItemBiosafetyChecklistOfSMTA2s,
    bool? Annex2ApprovalFlag,
    string Annex2ApprovalComment,
    Guid? Annex2OfSMTA2DocumentId,
    Guid? OriginalDocumentTemplateAnnex2OfSMTA2DocumentId,
    string Annex2OfSMTA2DocumentName,
    Guid? Annex2OfSMTA2SignatureId,
    Guid? OriginalDocumentTemplateBookingFormOfSMTA2DocumentId,
    FillingOption? BookingFormFillingOption,
    Guid? BookingFormOfSMTA2DocumentId,
    string BookingFormOfSMTA2DocumentName,
    Guid? BookingFormOfSMTA2SignatureId,
    string BookingForm2OfSMTA2SignatureString,
    List<BookingFormOfSMTADto> BookingForms,
    bool? BookingFormApprovalFlag,
    string BookingFormApprovalComment,
    bool IsSaveDraft,
    DateTime? BookingFormEstimateDateOfPickup,
    ShipmentDocumentOperationType? ShipmentDocumentOperationType,
    Guid? ShipmentDocumentId,
    string ShipmentDocumentNewName,
    List<ShipmentDocumentDto> BHFShipmentDocuments,
    List<ShipmentDocumentDto> QEShipmentDocuments,
    bool? WaitForArrivalConditionCheckApprovalFlag,
    string WaitForArrivalConditionCheckApprovalComment,
    string NewFeedback,
    List<FeedbackDto> Feedbacks,
    string WHODocumentRegistrationNumber,
    Guid? ReferenceId,
    FillingOption? BiosafetyChecklistFillingOption,
    //string OriginalDocumentTemplateBiosafetyChecklistOfSMTA2DocumentId,
    //string BiosafetyChecklistOfSMTA2DocumentId,
    //string BiosafetyChecklistOfSMTA2DocumentName,
    string BiosafetyChecklistOfSMTA2SignatureId,
    //string BiosafetyChecklistOfSMTA2SignatureString,
    bool BiosafetyChecklistOfSMTA2ApprovalFlag,
    string BiosafetyChecklistOfSMTA2ApprovalComment,
    Guid? OriginalDocumentTemplateBiosafetyChecklistOfSMTA2DocumentId,
    Guid? BioHubFacilityId,
    Guid? LaboratoryId,
    string NewBiosafetyChecklistThreadComment,
    List<BiosafetyChecklistThreadCommentDto> BiosafetyChecklistThreadComments,
    string NewBiosafetyChecklistThreadCommentFromDocument,
    DateTime? PreviousOperationDate,
    Guid? PreviousUserId,
    Guid? CurrentDownloadSMTA2DocumentId,
    bool? IsPast,
    DateTime? AssignedOperationDate,

    //# 54317
    string Annex2OfSMTA2SignatureText,
    string BookingFormOfSMTA2SignatureText,
    string BiosafetyChecklistOfSMTA2SignatureText
///////

);

