using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.WorklistFromBioHubHistoryItems.UpdateWorklistFromBioHubHistoryItem;

public record struct UpdateWorklistFromBioHubHistoryItemCommandResponse(WorklistFromBioHubHistoryItem WorklistFromBioHubHistoryItem) { }