using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialClinicalDetailsHistory.CreateMaterialClinicalDetailHistory;

public record struct CreateMaterialClinicalDetailHistoryCommandResponse(MaterialClinicalDetailHistory MaterialClinicalDetailHistory) { }