namespace WHO.BioHub.PublicData.Core.UseCases.InternationalTaxonomyClassifications.ReadInternationalTaxonomyClassification;

public record struct ReadInternationalTaxonomyClassificationQuery(Guid Id) { }