using WHO.BioHub.Shared.Dto;
using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.WorklistFromBioHubHistoryItems.DownloadWorklistFromBioHubHistoryItemFile;

public record struct DownloadWorklistFromBioHubHistoryItemFileQueryResponse(HttpResponseMessage DownloadedFile);