namespace WHO.BioHub.DataManagement.Core.UseCases.WorklistFromBioHubItemEvents.ListWorklistFromBioHubItemEvents;

public record struct ListWorklistFromBioHubItemEventsQuery(Guid WorklistFromBioHubItemId) { }