import { WorklistFromBioHubStatus } from "@/models/enums/WorklistFromBioHubStatus";
import { PermissionNames } from "./PermissionNames";

export const WorklistFromBioHubReadPermissionsByStatusList = new Map<
  WorklistFromBioHubStatus,
  string
>([
  [
    WorklistFromBioHubStatus.SubmitAnnex2OfSMTA2,
    PermissionNames.CanReadSubmitAnnex2OfSMTA2,
  ],
  [
    WorklistFromBioHubStatus.WaitingForAnnex2OfSMTA2SECsApproval,
    PermissionNames.CanReadWaitingForAnnex2OfSMTA2SECsApproval,
  ],
  [
    WorklistFromBioHubStatus.SubmitBiosafetyChecklistFormOfSMTA2,
    PermissionNames.CanReadSubmitBiosafetyChecklistFormOfSMTA2,
  ],
  [
    WorklistFromBioHubStatus.WaitForBiosafetyChecklistFormSMTA2BSFsApproval,
    PermissionNames.CanReadWaitForBiosafetyChecklistFormSMTA2BSFsApproval,
  ],
  [
    WorklistFromBioHubStatus.SubmitBookingFormOfSMTA2,
    PermissionNames.CanReadSubmitBookingFormOfSMTA2,
  ],
  [
    WorklistFromBioHubStatus.WaitForBookingFormSMTA2OPSsApproval,
    PermissionNames.CanReadWaitForBookingFormSMTA2OPSsApproval,
  ],
  [
    WorklistFromBioHubStatus.SubmitBHFSMTA2ShipmentDocuments,
    PermissionNames.CanReadBHFSMTA2ShipmentDocuments,
  ],
  [
    WorklistFromBioHubStatus.SubmitQESMTA2ShipmentDocuments,
    PermissionNames.CanReadQESMTA2ShipmentDocuments,
  ],
  [
    WorklistFromBioHubStatus.WaitForPickUpCompleted,
    PermissionNames.CanReadWaitForPickUpFromBioHubCompleted,
  ],
  [
    WorklistFromBioHubStatus.WaitForDeliveryCompleted,
    PermissionNames.CanReadWaitForDeliveryFromBioHubCompleted,
  ],
  [
    WorklistFromBioHubStatus.WaitForArrivalConditionCheck,
    PermissionNames.CanReadWaitForArrivalConditionFromBioHubCheck,
  ],
  [
    WorklistFromBioHubStatus.WaitForCommentQESendFeedback,
    PermissionNames.CanReadWaitForCommentQESendFeedback,
  ],
  [
    WorklistFromBioHubStatus.WaitForFinalApproval,
    PermissionNames.CanReadWaitForFinalApprovalFromBioHub,
  ],
  [
    WorklistFromBioHubStatus.ShipmentCompleted,
    PermissionNames.CanReadShipmentFromBioHubCompleted,
  ],
]);

export const WorklistFromBioHubReadPermissionsByStatusPastList = new Map<
  WorklistFromBioHubStatus,
  string
>([
  [
    WorklistFromBioHubStatus.SubmitAnnex2OfSMTA2,
    PermissionNames.CanReadSubmitAnnex2OfSMTA2Past,
  ],
  [
    WorklistFromBioHubStatus.WaitingForAnnex2OfSMTA2SECsApproval,
    PermissionNames.CanReadWaitingForAnnex2OfSMTA2SECsApprovalPast,
  ],
  [
    WorklistFromBioHubStatus.SubmitBiosafetyChecklistFormOfSMTA2,
    PermissionNames.CanReadSubmitBiosafetyChecklistFormOfSMTA2Past,
  ],
  [
    WorklistFromBioHubStatus.WaitForBiosafetyChecklistFormSMTA2BSFsApproval,
    PermissionNames.CanReadWaitForBiosafetyChecklistFormSMTA2BSFsApprovalPast,
  ],
  [
    WorklistFromBioHubStatus.SubmitBookingFormOfSMTA2,
    PermissionNames.CanReadSubmitBookingFormOfSMTA2Past,
  ],
  [
    WorklistFromBioHubStatus.WaitForBookingFormSMTA2OPSsApproval,
    PermissionNames.CanReadWaitForBookingFormSMTA2OPSsApprovalPast,
  ],
  [
    WorklistFromBioHubStatus.SubmitBHFSMTA2ShipmentDocuments,
    PermissionNames.CanReadBHFSMTA2ShipmentDocumentsPast,
  ],
  [
    WorklistFromBioHubStatus.SubmitQESMTA2ShipmentDocuments,
    PermissionNames.CanReadQESMTA2ShipmentDocumentsPast,
  ],
  [
    WorklistFromBioHubStatus.WaitForPickUpCompleted,
    PermissionNames.CanReadWaitForPickUpFromBioHubCompletedPast,
  ],
  [
    WorklistFromBioHubStatus.WaitForDeliveryCompleted,
    PermissionNames.CanReadWaitForDeliveryFromBioHubCompletedPast,
  ],
  [
    WorklistFromBioHubStatus.WaitForArrivalConditionCheck,
    PermissionNames.CanReadWaitForArrivalConditionFromBioHubCheckPast,
  ],
  [
    WorklistFromBioHubStatus.WaitForCommentQESendFeedback,
    PermissionNames.CanReadWaitForCommentQESendFeedbackPast,
  ],
  [
    WorklistFromBioHubStatus.WaitForFinalApproval,
    PermissionNames.CanReadWaitForFinalApprovalFromBioHubPast,
  ],
  [
    WorklistFromBioHubStatus.ShipmentCompleted,
    PermissionNames.CanReadShipmentFromBioHubCompletedPast,
  ],
]);
