namespace WHO.BioHub.DataManagement.Core.UseCases.InternationalTaxonomyClassifications.DeleteInternationalTaxonomyClassification;

public record struct DeleteInternationalTaxonomyClassificationCommand(Guid Id) { }