using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.ReadMaterialShippingInformationHistory;

public record struct ReadMaterialShippingInformationHistoryQueryResponse(MaterialShippingInformationHistory MaterialShippingInformationHistory) { }