using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.InternationalTaxonomyClassifications.CreateInternationalTaxonomyClassification;

public record struct CreateInternationalTaxonomyClassificationCommandResponse(InternationalTaxonomyClassification InternationalTaxonomyClassification) { }