namespace WHO.BioHub.DataManagement.Core.UseCases.InternationalTaxonomyClassifications.ListInternationalTaxonomyClassifications;

public record struct ListInternationalTaxonomyClassificationsQuery(Guid Id) { }