namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.CreateMaterialShippingInformationHistory;

public record struct CreateMaterialShippingInformationHistoryCommand { }