export enum DocumentFileType {
  SMTA1 = 0,
  SMTA2 = 1,
  Annex2OfSMTA1 = 2,
  Annex2OfSMTA2 = 3,
  BookingFormOfSMTA1 = 4,
  PackagingList = 5,
  NonCommercialInvoiceCatA = 6,
  NonCommercialInvoiceCatB = 7,
  DangerousGoodsDeclaration = 8,
  ExportPermit = 9,
  ImportPermit = 10,
  Other = 11,
  BiosafetyChecklist = 12,
  BookingFormOfSMTA2 = 13,
  WHOGuidance = 14,
}
