using WHO.BioHub.Shared.Enums;

namespace WHO.BioHub.DataManagement.Core.UseCases.Materials.CreateMaterial;

public record struct CreateMaterialCommand(
    string ReferenceNumber,
    string Name,
    string Description,
    double Temperature,
    string SampleId,
    string Lineage,
    string Variant,
    string VariantAssessment,
    string StrainDesignation,
    string Genotype,
    string Serotype,
    string DatabaseAccessionId,
    string OriginalGeneticSequence,
    string GSDCulturedMaterialCellLine1,
    string GSDCulturedMaterialCellLine2,
    string FacilityGSD,
    bool GMO,
    //string ProductionCellLine,
    string Infectivity,
    string ViralTiter,
    bool IsNew,
    Guid? TypeId,
    Guid? SuspectedEpidemiologicalOriginId,
    Guid? OriginalProductTypeId,
    Guid? TransportCategoryId,
    Guid? UnitOfMeasureId,
    Guid? UsagePermissionId,
    Guid? GeneticSequenceDataId,
    Guid? InternationalTaxonomyClassificationId,
    Guid? IsolationHostTypeId,
    Guid? CultivabilityTypeId,
    Guid? IsolationTechniqueTypeId,
    Guid? ProviderLaboratoryId,
    Guid? ProviderBioHubFacilityId,
    Guid? OwnerBioHubFacilityId,
    DateTime? CollectionDate,
    string Location,
    string PatientStatus,
    int? Age,
    Gender? Gender,
    Guid? UserId,
    int? ShipmentNumberOfVials,
    DateTime? DateOfBMEPPReceipt,
    string GSDCulturedMaterialCellLine3,
    Guid? ProductTypeId,
    string CulturingCellLine1,
    string CulturingCellLine2,
    string CulturingCellLine3,
    Readiness? BHFShareReadiness,
    YesNoOption? PublicShare
    );


