using WHO.BioHub.Models.Models;

namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.ListMaterialShippingInformationsHistory;

public record struct ListMaterialShippingInformationsHistoryQueryResponse(IEnumerable<MaterialShippingInformationHistory> MaterialShippingInformationsHistory) { }