namespace WHO.BioHub.DataManagement.Core.UseCases.MaterialShippingInformationsHistory.ListMaterialShippingInformationsHistory;

public record struct ListMaterialShippingInformationsHistoryQuery(Guid Id) { }